baseURL = "https://misrule.me/"
title = "The Lord of Misrule"
languageCode = "en-us"
theme = ""
enableRobotsTXT = true

[markup]
  [markup.highlight]
    noClasses = false

[taxonomies]
  tag = "tags"
  category = "categories"
