name: Build & Deploy Hugo to VPS

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: latest
        extended: true

    - name: Build site
      run: hugo --minify

    - name: Deploy via rsync
      uses: easingthemes/ssh-deploy@v2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST:     ${{ secrets.VPS_HOST }}
        REMOTE_USER:     ${{ secrets.VPS_USER }}
        SOURCE:          "public/"
        TARGET:          "/home/blackbird/sites/misrule"
        ARGS: "-avz --delete"

